### ISSUE TITLE
Increase Fireworm accuracy

### ISSUE THREAD

**Issue by Juanfrank** [Juanfrank/AA_CombatExtendedPatch#11]
It's crappy, nuff said.

**Comment by Juanfrank** [comment]
Also decreace burst interval between each burst.

**Comment by Breadbox2k19** [comment]
Please do note that by changing shot spread from 0.2 to 0.5(natural innate dispersal of shots from that weapon), you are actually making flamethrowers even LESS accurate. I doubt increasing sight efficiency would do much since mechanoids don't have much of a shooting stats. 

The interval between bursts also isn't changed in the edits from what I can tell, you'll want to reduce range cooldown time or aiming time for that to happen.
